from __future__ import annotations

import base64
import json
import os
import tempfile
import time
import urllib.error
import urllib.request
from contextlib import contextmanager
from dataclasses import dataclass
from typing import Callable, Iterable, Iterator, List, Literal, Optional, Sequence


ACCOUNT_URL = "https://music.163.com/api/nuser/account/get"
COOKIE_HEADERS = {
    "# HTTP Cookie File",
    "# Netscape HTTP Cookie File",
}
ValidationState = Literal["valid", "invalid", "unverified"]


class CookieFormatError(ValueError):
    """The pasted cookies.txt content is not usable for NetEase Music."""


@dataclass(frozen=True)
class NetscapeCookie:
    domain: str
    include_subdomains: bool
    path: str
    secure: bool
    expires: int
    name: str
    value: str
    http_only: bool = False

    def is_expired(self, now: Optional[int] = None) -> bool:
        current = int(time.time()) if now is None else int(now)
        return self.expires > 0 and self.expires <= current


@dataclass(frozen=True)
class CookieValidationResult:
    state: ValidationState
    message: str
    nickname: str = ""


def _matches_netease_domain(domain: str) -> bool:
    normalized = domain.strip().lower().lstrip(".")
    return (
        normalized == "163.com"
        or normalized == "music.163.com"
        or normalized.endswith(".music.163.com")
    )


def parse_netscape_cookies(
    text: str,
    *,
    now: Optional[int] = None,
) -> List[NetscapeCookie]:
    """Parse and filter Netscape cookies.txt content.

    Only non-expired cookies applicable to ``music.163.com`` are returned.
    A usable ``MUSIC_U`` login cookie is mandatory.
    """

    raw = (text or "").lstrip("\ufeff")
    lines = raw.splitlines()
    first_content = next((line.strip() for line in lines if line.strip()), "")
    if first_content not in COOKIE_HEADERS:
        raise CookieFormatError(
            "cookies.txt 首行必须是 # Netscape HTTP Cookie File 或 # HTTP Cookie File"
        )

    parsed: List[NetscapeCookie] = []
    expired_music_u = False
    current = int(time.time()) if now is None else int(now)
    for line_number, original in enumerate(lines, start=1):
        line = original.rstrip("\r\n")
        if not line.strip():
            continue
        http_only = False
        if line.startswith("#HttpOnly_"):
            line = line[len("#HttpOnly_") :]
            http_only = True
        elif line.lstrip().startswith("#"):
            continue

        fields = line.split("\t", 6)
        if len(fields) != 7:
            raise CookieFormatError(f"cookies.txt 第 {line_number} 行不是 Netscape 七列格式")
        domain, include_text, path, secure_text, expires_text, name, value = fields
        include_upper = include_text.upper()
        secure_upper = secure_text.upper()
        if include_upper not in ("TRUE", "FALSE") or secure_upper not in ("TRUE", "FALSE"):
            raise CookieFormatError(f"cookies.txt 第 {line_number} 行布尔字段无效")
        try:
            expires = int(expires_text)
        except ValueError as exc:
            raise CookieFormatError(f"cookies.txt 第 {line_number} 行过期时间无效") from exc
        if not name:
            raise CookieFormatError(f"cookies.txt 第 {line_number} 行缺少 Cookie 名称")
        if not _matches_netease_domain(domain):
            continue

        cookie = NetscapeCookie(
            domain=domain,
            include_subdomains=include_upper == "TRUE",
            path=path or "/",
            secure=secure_upper == "TRUE",
            expires=expires,
            name=name,
            value=value,
            http_only=http_only,
        )
        if cookie.is_expired(current):
            if cookie.name == "MUSIC_U":
                expired_music_u = True
            continue
        parsed.append(cookie)

    music_u = next((cookie for cookie in parsed if cookie.name == "MUSIC_U"), None)
    if music_u is None or not music_u.value:
        if expired_music_u:
            raise CookieFormatError("MUSIC_U 已过期，请重新导出 cookies.txt")
        raise CookieFormatError("未找到网易云 MUSIC_U，请登录网易云后重新导出 cookies.txt")
    return parsed


def serialize_netscape_cookies(cookies: Iterable[NetscapeCookie]) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Generated by SkyAutoMusic"]
    for cookie in cookies:
        domain = cookie.domain
        if cookie.http_only:
            domain = "#HttpOnly_" + domain
        lines.append(
            "\t".join(
                [
                    domain,
                    "TRUE" if cookie.include_subdomains else "FALSE",
                    cookie.path or "/",
                    "TRUE" if cookie.secure else "FALSE",
                    str(int(cookie.expires)),
                    cookie.name,
                    cookie.value,
                ]
            )
        )
    return "\n".join(lines) + "\n"


def cookie_request_header(cookies: Sequence[NetscapeCookie]) -> str:
    return "; ".join(f"{cookie.name}={cookie.value}" for cookie in cookies)


def validate_cookie_account(
    cookies: Sequence[NetscapeCookie],
    *,
    opener: Optional[Callable] = None,
    timeout: float = 12.0,
) -> CookieValidationResult:
    """Validate the login with NetEase.

    Explicit logged-out responses are invalid. Network failures are
    ``unverified`` so users may still save a locally valid cookie file.
    """

    request = urllib.request.Request(
        ACCOUNT_URL,
        headers={
            "Cookie": cookie_request_header(cookies),
            "Referer": "https://music.163.com/",
            "User-Agent": "Mozilla/5.0 SkyAutoMusic/1.0",
        },
    )
    open_request = opener or urllib.request.urlopen
    try:
        with open_request(request, timeout=timeout) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except (
        OSError,
        TimeoutError,
        urllib.error.URLError,
        json.JSONDecodeError,
        UnicodeDecodeError,
    ):
        return CookieValidationResult(
            "unverified",
            "Cookie 格式有效，但暂时无法联网验证；可以保存后在下载时重试",
        )

    account = payload.get("account")
    profile = payload.get("profile")
    if isinstance(account, dict) and account.get("id") and isinstance(profile, dict):
        nickname = str(profile.get("nickname") or "")
        suffix = f"：{nickname}" if nickname else ""
        return CookieValidationResult("valid", f"网易云账号验证成功{suffix}", nickname)
    return CookieValidationResult("invalid", "Cookie 登录已失效，请重新导出 cookies.txt")


def _dpapi_protect(data: bytes) -> bytes:
    try:
        import win32crypt
    except ImportError as exc:
        raise RuntimeError("缺少 Windows DPAPI 支持，无法安全保存 Cookie") from exc
    return win32crypt.CryptProtectData(
        data,
        "SkyAutoMusic NetEase Cookie",
        b"SkyAutoMusic/NetEase/v1",
        None,
        None,
        0,
    )


def _dpapi_unprotect(data: bytes) -> bytes:
    try:
        import win32crypt
    except ImportError as exc:
        raise RuntimeError("缺少 Windows DPAPI 支持，无法读取 Cookie") from exc
    _description, plaintext = win32crypt.CryptUnprotectData(
        data,
        b"SkyAutoMusic/NetEase/v1",
        None,
        None,
        0,
    )
    return plaintext


class NetEaseCookieStore:
    """Persist only encrypted, NetEase-scoped Netscape cookies."""

    def __init__(
        self,
        path: str,
        *,
        protect: Optional[Callable[[bytes], bytes]] = None,
        unprotect: Optional[Callable[[bytes], bytes]] = None,
    ):
        self.path = os.path.abspath(path)
        self._protect = protect or _dpapi_protect
        self._unprotect = unprotect or _dpapi_unprotect

    def save(
        self,
        canonical_text: str,
        validation: CookieValidationResult,
    ) -> None:
        cookies = parse_netscape_cookies(canonical_text)
        filtered_text = serialize_netscape_cookies(cookies)
        encrypted = self._protect(filtered_text.encode("utf-8"))
        payload = {
            "schemaVersion": 1,
            "ciphertext": base64.b64encode(encrypted).decode("ascii"),
            "validation": validation.state,
            "nickname": validation.nickname,
            "savedAt": int(time.time()),
        }
        directory = os.path.dirname(self.path)
        os.makedirs(directory, exist_ok=True)
        temporary_path = None
        try:
            with tempfile.NamedTemporaryFile(
                "w",
                encoding="utf-8",
                prefix=".netease-auth-",
                suffix=".tmp",
                dir=directory,
                delete=False,
            ) as handle:
                temporary_path = handle.name
                json.dump(payload, handle, ensure_ascii=False, indent=2)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary_path, self.path)
        except Exception:
            if temporary_path and os.path.exists(temporary_path):
                try:
                    os.unlink(temporary_path)
                except OSError:
                    pass
            raise

    def load_text(self) -> Optional[str]:
        if not os.path.isfile(self.path):
            return None
        with open(self.path, "r", encoding="utf-8") as handle:
            payload = json.load(handle)
        if int(payload.get("schemaVersion", 0)) != 1:
            raise RuntimeError("Cookie 存储版本不受支持，请清除后重新保存")
        encrypted = base64.b64decode(payload["ciphertext"], validate=True)
        plaintext = self._unprotect(encrypted).decode("utf-8")
        cookies = parse_netscape_cookies(plaintext)
        return serialize_netscape_cookies(cookies)

    def load_validation(self) -> CookieValidationResult:
        if not os.path.isfile(self.path):
            return CookieValidationResult("unverified", "未保存网易云 Cookie")
        try:
            with open(self.path, "r", encoding="utf-8") as handle:
                payload = json.load(handle)
            state = payload.get("validation")
            if state not in ("valid", "invalid", "unverified"):
                state = "unverified"
            nickname = str(payload.get("nickname") or "")
            if state == "valid":
                suffix = f"：{nickname}" if nickname else ""
                message = f"已加密保存并验证{suffix}"
            else:
                message = "已加密保存，尚未联网验证"
            return CookieValidationResult(state, message, nickname)
        except Exception:
            return CookieValidationResult("unverified", "Cookie 状态无法读取")

    def clear(self) -> None:
        try:
            os.unlink(self.path)
        except FileNotFoundError:
            pass

    @contextmanager
    def materialize_cookiefile(self) -> Iterator[Optional[str]]:
        text = self.load_text()
        if not text:
            yield None
            return
        path = None
        try:
            with tempfile.NamedTemporaryFile(
                "w",
                encoding="utf-8",
                prefix="sky-netease-cookie-",
                suffix=".txt",
                delete=False,
            ) as handle:
                path = handle.name
                handle.write(text)
            try:
                os.chmod(path, 0o600)
            except OSError:
                pass
            yield path
        finally:
            if path:
                try:
                    os.unlink(path)
                except OSError:
                    pass
